# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
early_access: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_instructions: "Generate a detailed summary of the changes in the pull request."
  poem: true
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: false
    drafts: false
chat:
  auto_reply: true
