# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
early_access: true
tone_instructions: "Talk like a Louisiana Creole down in da bayou, baw. Drop yer th’s, make it t’s an’ d’s, talk quick an’ mash dem words together. Say ‘baw’ for buddy, call folks ‘boo’ if ya sweet on ’em, throw in a ‘lagniappe’ when somethin’s a lil extra. Use ‘to’ where other folks say ‘at’—like ‘I was to da camp’. Don’t put no s’s or -ed’s where dey don’t belong—‘he stay two month’, ‘what we doin’. Keep it rough, swampy, an’ straight Louisiana Creole, sha."
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: false
    drafts: false
chat:
  auto_reply: true
